---
name: test

on:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure gh actions bot
        uses: ./

      - name: check results
        run: |
          git config --global user.name
          git config --global user.email

  stable:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure gh actions bot
        uses: peter-bread/setup-github-actions-bot@v2

      - name: check results
        run: |
          git config --global user.name
          git config --global user.email
